name: CI/CD for Frontend with Vercel

on:
  push:
    branches:
      - master  # change to 'main' if that's your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build the project
        run: npm run build
        working-directory: ./frontend

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --token=$VERCEL_TOKEN \
                 --confirm \
                 --org $VERCEL_ORG_ID \
                 --project $VERCEL_PROJECT_ID
        working-directory: ./frontend
