name: CI/CD for Frontend with Vercel

on:
  push:
    branches:
      - master  # change to 'main' if that's your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build the project
        run: CI='' npm run build
        working-directory: ./frontend

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
          vercel deploy --prod --token="$VERCEL_TOKEN"
        working-directory: ./frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

